--[[

	TechAge
	=======

	Copyright (C) 2019 Joachim Stolberg

	GPL v3
	See LICENSE.txt for more information
	
	TA Items Table

]]--

techage.Items = {
	techage_ta1 = "techage_ta1.png",
	iron = "techage:iron_ingot",
	charcoal = "techage:charcoal",
	lighter = "techage:lighter",
	ta1_gravelsieve = "techage:sieve3",
	hammer = "techage:hammer_bronze",
	meridium = "techage:meridium_ingot",
	ta1_hopper = "techage:hopper_ta1",
	wlanchip = "techage:ta4_wlanchip",
	tube = "techage:tubeS",
	----------------
	techage_ta2 = "techage_ta2.png",
	ta2_firebox = "techage:firebox",
	ta2_boiler = "techage:boiler2",
	ta2_cylinder = "techage:cylinder",
	ta2_flywheel = "techage:flywheel",
	ta2_steampipe = "techage:steam_pipeS",
	ta2_distributor = "techage:ta2_distributor_pas",
	ta2_pusher = "techage:ta2_pusher_pas",
	ta2_gravelrinser = "techage:ta2_rinser_pas",
	ta2_grinder = "techage:ta2_grinder_pas",
	ta2_autocrafter = "techage:ta2_autocrafter_pas",
	ta2_electronicfab = "techage:ta2_electronic_fab_pas",
	ta2_gravelsieve = "techage:ta2_gravelsieve_pas",
	ta2_liquidsampler = "techage:ta2_liquidsampler_pas",
	ta2_rinser = "techage:ta2_rinser_pas",
	ta2_chest = "techage:chest_ta2",
	ta2_forceload = "techage:forceload",
	---------------------
	techage_ta3 = "techage_ta3.png",
	ta3_firebox = "techage:coalfirebox",
	ta3_oilbox = "techage:oilfirebox",
	ta3_boiler = "techage:coalboiler_top",
	ta3_turbine = "techage:turbine",
	ta3_generator = "techage:generator",
	ta3_cooler = "techage:cooler",
	ta3_distributor = "techage:ta3_distributor_pas",
	ta3_pusher = "techage:ta3_pusher_pas",
	ta3_gravelrinser = "techage:ta3_rinser_pas",
	ta3_grinder = "techage:ta3_grinder_pas",
	ta3_autocrafter = "techage:ta3_autocrafter_pas",
	ta3_electronicfab = "techage:ta3_electronic_fab_pas",
	ta3_gravelsieve = "techage:ta3_gravelsieve_pas",
	ta3_liquidsampler = "techage:ta3_liquidsampler_pas",
	ta3_funnel = "techage:ta3_funnel",
	ta3_powercable = "techage:electric_cableS",
	ta3_powerline = "techage:power_lineS",
	ta3_powerswitch = "techage:powerswitch",
	ta3_powerswitchsmall = "techage:powerswitchsmall",
	ta3_powerjunction = "techage:electric_junction0",
	ta3_powerpole = "techage:power_pole3",
	ta3_powerpole2 = "techage:power_pole2",
	ta3_powerpole4 = "techage:power_pole",
	ta3_powerswitchbox = "techage:powerswitch_box",
	ta3_powerterminal = "techage:ta3_power_terminal",
	ta3_trowel = "techage:trowel",
	ta3_tinygenerator = "techage:tiny_generator",
	ta3_akkublock = "techage:ta3_akku",
	ta3_furnace = "techage:ta3_furnace_pas",
	ta3_furnacefirebox = "techage:furnace_firebox",
	ta3_booster = "techage:ta3_booster",
	ta3_oilexplorer = "techage:oilexplorer",
	ta3_drillbox = "techage:ta3_drillbox_pas",
	ta3_pumpjack = "techage:ta3_pumpjack_pas",
	ta3_drillbit = "techage:oil_drillbit",
	ta3_end_wrench = "techage:end_wrench",
	ta3_tank = "techage:ta3_tank",
	ta3_pump = "techage:t3_pump",
	oiltank = "techage:oiltank",
	----------------------------
	ta3_button = "techage:ta3_button_off",
	ta3_cartdetector = "techage:ta3_cartdetector_off",
	ta3_detector = "techage:ta3_detector_off",
	ta3_logic = "techage:ta3_logic",
	ta3_nodedetector = "techage:ta3_nodedetector_off",
	ta3_playerdetector = "techage:ta3_playerdetector_off",
	ta3_repeater = "techage:ta3_repeater",
	ta3_sequencer = "techage:ta3_sequencer",
	ta3_timer = "techage:ta3_timer",
	ta3_terminal = "techage:terminal2",
	ta3_signallamp = "techage:signal_lamp_off",
	ta3_doorblock = "techage:doorblock20",
	ta3_programmer = "techage:programmer",
	----------------------------
	techage_ta4 = "techage_ta4.png",
	ta4_windturbine = "techage:ta4_wind_turbine",
	ta4_pillar = "techage:pillar",
	ta4_blinklamp = "techage:rotor_signal_lamp_off",
	ta4_nacelle = "techage:ta4_wind_turbine_nacelle",
	ta4_minicell = "techage:ta4_solar_minicell",
	ta4_pipe = "techage:ta4_pipeS", 
	ta4_junctionpipe = "techage:ta4_junctionpipe25", 
	ta4_pipeinlet = "techage:ta4_pipe_inlet", 
	ta4_turbine = "techage:ta4_turbine",
	ta4_generator = "techage:ta4_generator",
	ta4_heatexchanger = "techage:heatexchanger3", 
	ta4_powercable = "techage:ta4_power_cableS",
	ta4_powerbox = "techage:ta4_power_box",
	ta4_solarmodule = "techage:ta4_solar_module",
	ta4_solarcarrier = "techage:ta4_solar_carrier",
	ta4_solar_inverter = "techage:ta4_solar_inverter",
	techage_ta4_solar = "techage_ta4_solar.png",
	ta4_hydrogen = "techage_hydrogen_inv.png",
	ta4_electrolyzer = "techage:ta4_electrolyzer",
	ta4_fuelcell = "techage:ta4_fuelcell",
	ta4_tank = "techage:ta4_tank",
	ta4_pump = "techage:t4_pump",
	--ta4_ "", 
}
