--[[

	TechAge
	=======

	Copyright (C) 2019 Joachim Stolberg

	AGPL v3
	See LICENSE.txt for more information

	TA Items Table

]]--

techage.Items = {
	techage_ta1 = "techage_ta1.png",
	iron = "techage:iron_ingot",
	charcoal = "techage:charcoal",
	lighter = "techage:lighter",
	ta1_gravelsieve = "techage:sieve3",
	hammer = "techage:hammer_bronze",
	meridium = "techage:meridium_ingot",
	baborium = "techage:stone_with_baborium",
	bauxite = "techage:bauxite_stone",
	usmium = "techage:usmium_nuggets",
	basalt = "techage:basalt_stone",
	oil = "techage:oil_source",
	ta1_hopper = "techage:hopper_ta1",
	wlanchip = "techage:ta4_wlanchip",
	tube = "techage:tubeS",
	concentrator = "techage:concentrator27",
	ta1_sluice = "techage:ta1_sluice_closed",
	ta1_sluice_handle = "techage:ta1_sluice_handle_closed",
	ta1_board1 = "techage:ta1_board1_apple",
	ta1_board2 = "techage:ta1_board2_apple",
	----------------
	techage_ta2 = "techage_ta2.png",
	ta2_firebox = "techage:firebox",
	ta2_boiler = "techage:boiler2",
	ta2_cylinder = "techage:cylinder",
	ta2_flywheel = "techage:flywheel",
	ta2_steampipe = "techage:steam_pipeS",
	ta2_distributor = "techage:ta2_distributor_pas",
	ta2_pusher = "techage:ta2_pusher_pas",
	ta2_gravelrinser = "techage:ta2_rinser_pas",
	ta2_grinder = "techage:ta2_grinder_pas",
	ta2_quarry = "techage:ta2_quarry_pas",
	ta2_autocrafter = "techage:ta2_autocrafter_pas",
	ta2_electronicfab = "techage:ta2_electronic_fab_pas",
	ta2_gravelsieve = "techage:ta2_gravelsieve_pas",
	ta2_liquidsampler = "techage:ta2_liquidsampler_pas",
	ta2_rinser = "techage:ta2_rinser_pas",
	ta2_chest = "techage:chest_ta2",
	ta2_forceload = "techage:forceload",
	ta2_driveaxle = "techage:axle",
	ta2_generator = "techage:ta2_generator_off",
    ta2_winch = "techage:ta2_winch",
    ta2_weight_chest = "techage:ta2_weight_chest",
	---------------------
	techage_ta3 = "techage_ta3.png",
	techage_ta31 = "techage_ta3b.png",
	ta3_firebox = "techage:coalfirebox",
	ta3_oilbox = "techage:oilfirebox",
	ta3_boiler = "techage:coalboiler_top",
	ta3_turbine = "techage:turbine",
	ta3_generator = "techage:generator",
	ta3_cooler = "techage:cooler",
	ta3_distributor = "techage:ta3_distributor_pas",
	ta3_pusher = "techage:ta3_pusher_pas",
	ta3_gravelrinser = "techage:ta3_rinser_pas",
	ta3_grinder = "techage:ta3_grinder_pas",
	ta3_quarry = "techage:ta3_quarry_pas",
	ta3_autocrafter = "techage:ta3_autocrafter_pas",
	ta3_electronicfab = "techage:ta3_electronic_fab_pas",
	ta3_gravelsieve = "techage:ta3_gravelsieve_pas",
	ta3_liquidsampler = "techage:ta3_liquidsampler_pas",
	ta3_powercable = "techage:electric_cableS",
	ta3_powerline = "techage:power_lineS",
	ta3_powerswitch = "techage:powerswitch",
	ta3_powerswitchsmall = "techage:powerswitchsmall",
	ta3_powerjunction = "techage:electric_junction0",
	ta3_powerpole = "techage:power_pole3",
	ta3_powerpole2 = "techage:power_pole2",
	ta3_powerpole4 = "techage:power_pole",
	ta3_powerswitchbox = "techage:powerswitch_box",
	ta3_powerterminal = "techage:ta3_power_terminal",
	ta3_trowel = "techage:trowel",
	ta3_screwdriver = "techage:screwdriver",
	ta3_tinygenerator = "techage:tiny_generator",
	ta3_akkublock = "techage:ta3_akku",
	ta3_furnace = "techage:ta3_furnace_pas",
	ta3_furnacefirebox = "techage:furnace_firebox",
	ta3_booster = "techage:ta3_booster",
	ta3_oilexplorer = "techage:oilexplorer",
	ta3_drillbox = "techage:ta3_drillbox_pas",
	ta3_pumpjack = "techage:ta3_pumpjack_pas",
	ta3_drillbit = "techage:oil_drillbit",
	ta3_end_wrench = "techage:end_wrench",
	ta3_tank = "techage:ta3_tank",
	ta3_pump = "techage:t3_pump",
	oiltank = "techage:oiltank",
	reboiler = "techage:ta3_reboiler",
	ta3_filler = "techage:filler",
	tank_cart = "techage:tank_cart",
	chest_cart = "techage:chest_cart",
	----------------------------
	ta3_button = "techage:ta3_button_off",
	ta3_cartdetector = "techage:ta3_cartdetector_off",
	ta3_detector = "techage:ta3_detector_off",
	ta3_logic = "techage:ta3_logic",
	ta3_nodedetector = "techage:ta3_nodedetector_off",
	ta3_playerdetector = "techage:ta3_playerdetector_off",
	ta3_lightdetector = "techage:ta3_lightdetector_off",
	ta3_repeater = "techage:ta3_repeater",
	ta3_sequencer = "techage:ta3_sequencer",
	ta3_timer = "techage:ta3_timer",
	ta3_terminal = "techage:terminal2",
	ta3_signallamp = "techage:signal_lamp_off",
	ta3_doorblock = "techage:doorblock20",
	ta3_programmer = "techage:programmer",
	ta3_doorcontroller = "techage:ta3_doorcontroller",
	ta3_drill_pipe_wrench = "techage:ta3_drill_pipe_wrench",
	ta3_pipe = "techage:ta3_pipeS",
	ta3_pipe_wall_entry = "techage:ta3_pipe_wall_entry",
	ta3_mesecons_converter = "techage:ta3_mesecons_converter",
	ta3_valve = "techage:ta3_valve_closed",
	ta3_motor = "techage:ta3_motor_off",
	ta3_injector = "techage:ta3_injector_pas",
	----------------------------
	techage_ta4 = "techage_ta4.png",
	techage_ta4c = "techage_ta4c.png",
	ta4_windturbine = "techage:ta4_wind_turbine",
	ta4_pillar = "techage:pillar",
	ta4_blinklamp = "techage:rotor_signal_lamp_off",
	ta4_nacelle = "techage:ta4_wind_turbine_nacelle",
	ta4_minicell = "techage:ta4_solar_minicell",
	ta4_pipe = "techage:ta4_pipeS",
	ta4_tube = "techage:ta4_tubeS",
	ta4_junctionpipe = "techage:ta4_junctionpipe25",
	ta4_pipeinlet = "techage:ta4_pipe_inlet",
	ta4_turbine = "techage:ta4_turbine",
	ta4_generator = "techage:ta4_generator",
	ta4_heatexchanger = "techage:heatexchanger3",
	ta4_powercable = "techage:ta4_power_cableS",
	ta4_powerbox = "techage:ta4_power_box",
	ta4_solarmodule = "techage:ta4_solar_module",
	ta4_solarcarrier = "techage:ta4_solar_carrier",
	ta4_solar_inverter = "techage:ta4_solar_inverter",
	techage_ta4_solar = "techage_ta4_solar.png",
	ta4_hydrogen = "techage_hydrogen_inv.png",
	ta4_electrolyzer = "techage:ta4_electrolyzer",
	ta4_fuelcell = "techage:ta4_fuelcell",
	ta4_reactor = "techage:ta4_reactor",
	ta4_tank = "techage:ta4_tank",
	ta4_pump = "techage:t4_pump",
	ta4_doser = "techage:ta4_doser",
	ta4_silo = "techage:ta4_silo",
	ta4_fillerpipe = "techage:ta4_reactor_fillerpipe",
	ta4_reactorstand = "techage:ta4_reactor_stand",
	ta4_reactorbase = "techage:ta4_reactor_base",
	ta4_furnaceheater = "techage:furnace_heater",
	ta4_waterpump = "techage:t4_waterpump",
	ta4_icta_controller = "techage:ta4_icta_controller",
	ta4_battery = "techage:ta4_battery",
	ta4_display = "techage:ta4_display",
	ta4_displayXL = "techage:ta4_displayXL",
	ta4_signaltower = "techage:ta4_signaltower",
	ta4_lua_controller = "techage:ta4_lua_controller",
	ta4_lua_server = "techage:ta4_server",
	ta4_sensor_chest = "techage:ta4_sensor_chest",
	ta4_terminal = "techage:ta4_terminal",
	ta4_button = "techage:ta4_button_off",
	ta4_playerdetector = "techage:ta4_playerdetector_off",
	ta4_collector = "techage:ta4_collector",
	ta4_pusher = "techage:ta4_pusher_pas",
	ta4_distributor = "techage:ta4_distributor_pas",
	ta4_high_performance_distributor = "techage:ta4_high_performance_distributor_pas",
	ta4_gravelsieve = "techage:ta4_gravelsieve_pas",
	ta4_grinder = "techage:ta4_grinder_pas",
	ta4_detector = "techage:ta4_detector_off",
	ta4_chest = "techage:chest_ta4",
	ta4_8x2000_chest = "techage:ta4_chest",
	ta4_growlight = "techage:growlight_on",
	ta4_streetlamp = "techage_ta4_streetlamp.png",
	ta4_industriallamp = "techage:industriallamp4_off",
	ta4_quarry = "techage:ta4_quarry_pas",
	ta4_electronicfab = "techage:ta4_electronic_fab_pas",
	ta4_injector = "techage:ta4_injector_pas",
	ta4_liquid_filter = "techage_ta4_filter.png",
	ta4_recycler = "techage:ta4_recycler_pas",
	ta4_waterinlet = "techage:ta4_waterinlet",
	ta4_laser = "techage:ta4_laser_emitter",
	ta4_concentrator = "techage:ta4_concentrator27",
	ta4_electricmeter = "techage:ta4_electricmeter",
	ta4_transformer = "techage:ta4_transformer",
	power_reduction = "techage_power_reduction.png",
	ta4_button_2x = "techage:ta4_button_2x",
	ta4_button_4x = "techage:ta4_button_4x",
	ta4_sequencer = "techage:ta4_sequencer",
	ta4_movecontroller = "techage:ta4_movecontroller",
	ta4_turncontroller = "techage:ta4_turncontroller",
	ta4_signallamp_2x = "techage:ta4_signallamp_2x",
	ta4_signallamp_4x = "techage:ta4_signallamp_4x",
	ta4_terminal = "techage:terminal3",
	ta4_autocrafter = "techage:ta4_autocrafter_pas",
	ta4_recipeblock = "techage:ta4_recipeblock",
	----------------------------
	techage_ta5 = "techage:ta5_fr_nucleus",
	ta5_flycontroller = "techage:ta5_flycontroller",
	ta5_aichip = "techage:ta5_aichip",
	ta5_tele_pipe = "techage:ta5_tele_pipe",
	ta5_tele_tube = "techage:ta5_tele_tube",
	ta5_chest = "techage:ta5_hl_chest",
	ta5_tank = "techage:ta5_hl_tank",
	ta5_magnet = "techage:ta5_magnet1",
	ta5_pump = "techage:ta5_pump",
	ta5_fr_shell = "techage:ta5_fr_shell",
	ta5_fr_nucleus = "techage:ta5_fr_nucleus",
	ta5_fr_controller = "techage:ta5_fr_controller_pas",
}

function techage.add_manual_items(table_with_items)
	for name, tbl in pairs(table_with_items) do
		techage.Items[name] = tbl
	end
end
