techage.OggFileList = {
	"autobahn_motor",                          -- ./mods/autobahn/sounds
	"signs_bot_ping",                          -- ./mods/signs_bot/sounds
	"signs_bot_go_away",                       -- ./mods/signs_bot/sounds
	"signs_bot_step",                          -- ./mods/signs_bot/sounds
	"signs_bot_pong",                          -- ./mods/signs_bot/sounds
	"signs_bot_error",                         -- ./mods/signs_bot/sounds
	"normal2",                                 -- ./mods/hyperloop/sounds
	"up2",                                     -- ./mods/hyperloop/sounds
	"down2",                                   -- ./mods/hyperloop/sounds
	"ele_norm",                                -- ./mods/hyperloop/sounds
	"door",                                    -- ./mods/hyperloop/sounds
	"hyperloop_crowbar",                       -- ./mods/hyperloop/sounds
	"ele_door",                                -- ./mods/hyperloop/sounds
	"techage_watermill",                       -- ./mods/techage/sounds
	"techage_button",                          -- ./mods/techage/sounds
	"techage_steamengine",                     -- ./mods/techage/sounds
	"techage_generator",                       -- ./mods/techage/sounds
	"techage_gasflare",                        -- ./mods/techage/sounds
	"techage_explore",                         -- ./mods/techage/sounds
	"techage_mill",                            -- ./mods/techage/sounds
	"techage_reactor",                         -- ./mods/techage/sounds
	"techage_valve",                           -- ./mods/techage/sounds
	"techage_oildrill",                        -- ./mods/techage/sounds
	"techage_turbine",                         -- ./mods/techage/sounds
	"techage_booster",                         -- ./mods/techage/sounds
	"techage_quarry",                          -- ./mods/techage/sounds
	"techage_reboiler",                        -- ./mods/techage/sounds
	"jetpack_loop",                            -- ./mods/jetpack/sounds
	"paperflip1",                              -- ./mods/unified_inventory/sounds
	"teleport",                                -- ./mods/unified_inventory/sounds
	"electricity",                             -- ./mods/unified_inventory/sounds
	"owl",                                     -- ./mods/unified_inventory/sounds
	"click",                                   -- ./mods/unified_inventory/sounds
	"birds",                                   -- ./mods/unified_inventory/sounds
	"paperflip2",                              -- ./mods/unified_inventory/sounds
	"dingdong",                                -- ./mods/unified_inventory/sounds
	"trash",                                   -- ./mods/unified_inventory/sounds
	"trash_all",                               -- ./mods/unified_inventory/sounds
	"ta4_jetpack",                             -- ./mods/ta4_jetpack/sounds
	"ta4_jetpack_alarm",                       -- ./mods/ta4_jetpack/sounds
	"ta4_jetpack_on",                          -- ./mods/ta4_jetpack/sounds
	"player_damage",                           -- ./games/minetest_game/mods/player_api/sounds
	"env_sounds_water",                        -- ./games/minetest_game/mods/env_sounds/sounds
	"env_sounds_lava",                         -- ./games/minetest_game/mods/env_sounds/sounds
	"doors_door_close",                        -- ./games/minetest_game/mods/doors/sounds
	"doors_steel_door_close",                  -- ./games/minetest_game/mods/doors/sounds
	"doors_door_open",                         -- ./games/minetest_game/mods/doors/sounds
	"doors_fencegate_close",                   -- ./games/minetest_game/mods/doors/sounds
	"doors_glass_door_close",                  -- ./games/minetest_game/mods/doors/sounds
	"doors_fencegate_open",                    -- ./games/minetest_game/mods/doors/sounds
	"doors_glass_door_open",                   -- ./games/minetest_game/mods/doors/sounds
	"doors_steel_door_open",                   -- ./games/minetest_game/mods/doors/sounds
	"fire_flint_and_steel",                    -- ./games/minetest_game/mods/fire/sounds
	"fire_large",                              -- ./games/minetest_game/mods/fire/sounds
	"fire_fire",                               -- ./games/minetest_game/mods/fire/sounds
	"fire_extinguish_flame",                   -- ./games/minetest_game/mods/fire/sounds
	"fire_small",                              -- ./games/minetest_game/mods/fire/sounds
	"tnt_ignite",                              -- ./games/minetest_game/mods/tnt/sounds
	"tnt_gunpowder_burning",                   -- ./games/minetest_game/mods/tnt/sounds
	"tnt_explode",                             -- ./games/minetest_game/mods/tnt/sounds
	"carts_cart_new",                          -- ./games/minetest_game/mods/carts/sounds
	"carts_cart_moving",                       -- ./games/minetest_game/mods/carts/sounds
	"xpanes_steel_bar_door_open",              -- ./games/minetest_game/mods/xpanes/sounds
	"xpanes_steel_bar_door_close",             -- ./games/minetest_game/mods/xpanes/sounds
	"default_break_glass",                     -- ./games/minetest_game/mods/default/sounds
	"default_dig_dig_immediate",               -- ./games/minetest_game/mods/default/sounds
	"default_dig_cracky",                      -- ./games/minetest_game/mods/default/sounds
	"default_dig_choppy",                      -- ./games/minetest_game/mods/default/sounds
	"default_water_footstep",                  -- ./games/minetest_game/mods/default/sounds
	"player_damage",                           -- ./games/minetest_game/mods/default/sounds
	"default_gravel_footstep",                 -- ./games/minetest_game/mods/default/sounds
	"default_dig_metal",                       -- ./games/minetest_game/mods/default/sounds
	"default_gravel_dug",                      -- ./games/minetest_game/mods/default/sounds
	"default_hard_footstep",                   -- ./games/minetest_game/mods/default/sounds
	"default_sand_footstep",                   -- ./games/minetest_game/mods/default/sounds
	"default_grass_footstep",                  -- ./games/minetest_game/mods/default/sounds
	"default_chest_close",                     -- ./games/minetest_game/mods/default/sounds
	"default_cool_lava",                       -- ./games/minetest_game/mods/default/sounds
	"default_place_node_hard",                 -- ./games/minetest_game/mods/default/sounds
	"default_ice_dug",                         -- ./games/minetest_game/mods/default/sounds
	"default_dig_crumbly",                     -- ./games/minetest_game/mods/default/sounds
	"default_tool_breaks",                     -- ./games/minetest_game/mods/default/sounds
	"default_ice_footstep",                    -- ./games/minetest_game/mods/default/sounds
	"default_dig_cracky",                      -- ./games/minetest_game/mods/default/sounds
	"default_chest_open",                      -- ./games/minetest_game/mods/default/sounds
	"default_gravel_dig",                      -- ./games/minetest_game/mods/default/sounds
	"default_dig_oddly_breakable_by_hand",     -- ./games/minetest_game/mods/default/sounds
	"default_dug_metal",                       -- ./games/minetest_game/mods/default/sounds
	"default_dirt_footstep",                   -- ./games/minetest_game/mods/default/sounds
	"default_dig_choppy",                      -- ./games/minetest_game/mods/default/sounds
	"default_glass_footstep",                  -- ./games/minetest_game/mods/default/sounds
	"default_snow_footstep",                   -- ./games/minetest_game/mods/default/sounds
	"default_place_node",                      -- ./games/minetest_game/mods/default/sounds
	"default_dig_snappy",                      -- ./games/minetest_game/mods/default/sounds
	"default_dug_node",                        -- ./games/minetest_game/mods/default/sounds
	"default_metal_footstep",                  -- ./games/minetest_game/mods/default/sounds
	"default_ice_dig",                         -- ./games/minetest_game/mods/default/sounds
	"default_place_node_metal",                -- ./games/minetest_game/mods/default/sounds
	"default_wood_footstep",                   -- ./games/minetest_game/mods/default/sounds
	"default_furnace_active",                  -- ./games/minetest_game/mods/default/sounds
	"default_item_smoke",                      -- ./games/minetest_game/mods/default/sounds
}
